### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by alienxp03** [Xe0n0/FinderTweak#1]
is this version working? by default in Mavericks, Command + Num is to change view as Icon, List, etc. or perhaps change it to Ctrl + Num maybe?

**Comment by Xe0n0** [comment]
@alienxp03 
I see this version on my Mac, and my Finder.app version is 10.9. I am still using the latest Developer Preview of Mavericks. What's your Finder.app version? Have you relaunched your Finder?

I know `⌘ + num` are used to change view types by default, but I wanna have the same behavior with others apps like Firefox, Chrome, Sublime Text, TextMate, iTerm... Maybe I can release another build using `Ctrl + num`

**Comment by alienxp03** [comment]
I am using Finder 10.9. But using official Mavericks, not the Developer Preview version. I did relaunch my Finder, even force kill the process and restart my Mac. still not working. It's still using ⌘ + num to change view types, which is the default.

If I understand this correctly, installing your plugin would override the default ⌘ + num from changing view to changing tab, right? If i'm the only experiencing the problem, I must have done something wrong, or installed some kind of weird plugin somewhere.

**Comment by Xe0n0** [comment]
@alienxp03 
Have you installed SIMBL, which is a dependency of the plugin?

Yes, the plugin will override the default behavior.

**Comment by alienxp03** [comment]
I did install both SIMBL and your plugin. multiple times too, since I just want to be sure. and I'm using the SafariTabSwitching plugin too. it works fine.

I'll check again tomorrow. probably the SIMBL plugin

**Comment by Xe0n0** [comment]
@alienxp03 
Could you help me check if the file FinderTabSwitching.bundle exists at PATH `/Library/Application Support/SIMBL/Plugins/` ? Thanks.

**Comment by alienxp03** [comment]
the bundle does not exist in /Library/Application Support/SIMBL/Plugins. it only exist in ~/Library/Application Support/SIMBL/Plugins/. 

tried to manually copy the FinderTabSwitching.bundle to /Library/Application Support/SIMBL/Plugins/, but it doesn't seem to make any different

**Comment by Xe0n0** [comment]
@alienxp03 
When relaunch Finder.app, you are supposed to see logs in Console.app of SIMBL trying to load the bundle. Could you help me check the log?

**Comment by alienxp03** [comment]
The log when I'm trying to install the plugin

```
Nov  7 11:33:58 tokwans-MacBook-Pro.local Installer[12075]: *** WARNING: -[NSImage compositeToPoint:operation:] is deprecated in MacOSX 10.8 and later. Please use -[NSImage drawAtPoint:fromRect:operation:fraction:] instead.
Nov  7 11:33:58 tokwans-MacBook-Pro.local Installer[12075]: *** WARNING: -[NSImage compositeToPoint:fromRect:operation:] is deprecated in MacOSX 10.8 and later. Please use -[NSImage drawAtPoint:fromRect:operation:fraction:] instead.
Nov  7 11:33:58 tokwans-MacBook-Pro.local Installer[12075]: *** WARNING: -[NSImage compositeToPoint:operation:fraction:] is deprecated in MacOSX 10.8 and later. Please use -[NSImage drawAtPoint:fromRect:operation:fraction:] instead.
Nov  7 11:33:58 tokwans-MacBook-Pro.local Installer[12075]: *** WARNING: -[NSImage compositeToPoint:fromRect:operation:fraction:] is deprecated in MacOSX 10.8 and later. Please use -[NSImage drawAtPoint:fromRect:operation:fraction:] instead.
```

The log when I've finished the installation

```
Nov  7 11:34:20 tokwans-MacBook-Pro.local launchservicesd[51]: Application App:"Installer" asn:0x0-1ef1ef pid:12075 refs=7 @ 0x7fc261d74240 tried to be brought forward, but isn't in fPermittedFrontApps ( ( "LSApplication:0x0-0x1f11f1 pid=12086 "SecurityAgent"")), so denying. : LASSession.cp #1481 SetFrontApplication() q=LSSession 100005/0x186a5 queue
Nov  7 11:34:20 tokwans-MacBook-Pro.local WindowServer[89]: [cps/setfront] Failed setting the front application to Installer, psn 0x0-0x1ef1ef, securitySessionID=0x186a5, err=-13066
```

The log when I relaunch the finder

```
Nov  7 11:34:44 tokwans-MacBook-Pro.local Finder[12099]: Finder Tab Switching Loaded
```

**Comment by Xe0n0** [comment]
Wired... I gonna install the newest Mavericks and have a try...

**Comment by Xe0n0** [comment]
Hey, when there is only one tab, ⌘ + num still function as changing the type of views. Have you first created a new tab by ⌘ + T ?

**Comment by alienxp03** [comment]
I'm wired too. have you installed latest Mavericks? I've created 3-4 tabs, and ⌘ + num still functioning as changing the type of views.

**Comment by Xe0n0** [comment]
@alienxp03 
I've just installed the latest Mavericks, and it works fine.

**Comment by alienxp03** [comment]
I guess its my machine. I'll troubleshoot when I have some free time. if it works with everyone else, you can probably close this issue. and many thanks for your help :)

**Comment by Xe0n0** [comment]
@alienxp03 
Hi, I suggest you try EasySIMBL https://github.com/norio-nomura/EasySIMBL/ instead of the old SIMBL plugin. It's easier to use.

**Comment by alienxp03** [comment]
thanks. tried it. and it still not working. I tried installing another plugin called ColorfulSidebar. Both are enabled on EasySIMBL, but only ColorfulSidebar is working. FinderTabSwitching still not working for me though

![screen shot 2013-11-21 at 10 54 49 pm](https://f.cloud.github.com/assets/672704/1592513/e5a943c0-52bc-11e3-917d-adb6a6745778.png)

**Comment by Xe0n0** [comment]
How about turn on Use SIMBL?

**Comment by alienxp03** [comment]
Tried different varieties including Use SIMBL, however, still not working.

**Comment by Xe0n0** [comment]
@alienxp03 
Is the plugin in `~/Library/Application Support/SIMBL/Plugins`?
EasySIMBL won't load plugins from `/Library/Application Support/SIMBL/Plugins`

**Comment by alienxp03** [comment]
Yup. it is in `~/Library/Application Support/SIMBL/Plugins`
